version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: asset-postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: assetdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres