spring:
  application:
    name: "interview-materials-feature-test-inditex"
  r2dbc:
    url: r2dbc:h2:mem:///testdb;MODE=PostgreSQL;DB_CLOSE_DELAY=-1
    username: sa
    password:

management:
  endpoints:
    web:
      exposure:
        include: health, info
  endpoint:
    health:
      show-details: always

logging:
  level:
    org.springframework.boot.autoconfigure.r2dbc: DEBUG
    io.r2dbc: DEBUG
